version: 2
jobs:
  build:
    working_directory: ~/todo-cljs-api
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: todo-cljs-api-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: todo-cljs-api-{{ checksum "project.clj" }}
      - run: lein test:once