version: 2
jobs:
  build:
    working_directory: ~/todo-cljs-api
    
    docker:
      - image: circleci/clojure:lein-2.7.1
        environment:
        - PG_HOST: localhost
        - PG_USER: ubuntu

      - image: postgres:9.6
        environment:
        - POSTGRES_USER: ubuntu
        - POSTGRES_DB: todo_cljs_test

    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          key: todo-cljs-api-{{ checksum "project.clj" }}

      - run:
          name: Install dependencies
          command: lein deps

      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: todo-cljs-api-{{ checksum "project.clj" }}

      - run: 
          name: Run all tests
          command: lein with-profile +test test :all
          environment:
          - DB_NAME: todo_cljs_test
          - DB_TYPE: postgresql
          - DB_HOST: localhost
          - DB_USER: ubuntu
